version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: always
  api2:
    image: yitinglee/blog-api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links: 
      - mongo
    networks:
      - backend
    restart: always
  app:
    image: yitinglee/blog-app
    ports:
      - "4200:4200"
    restart: always
networks:
  backend:
    driver: "bridge"
